trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'vecjar/python-aca-app:latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    
- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt
  displayName: 'Install Python dependencies'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: 'vecjar/python-aca-app'
    dockerfile: 'app/Dockerfile'
    containerRegistry: 'DockerHub'
    tags: 'latest'

- task: AzureWebApp@1
  displayName: 'Deploy Docker Container'
  inputs:
    azureSubscription: 'YourAzureServiceConnection'
    appName: '$(webAppName)'
    package: ''
    appSettings: '-DOCKER_CUSTOM_IMAGE_NAME $(containerImage)'

