trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerImage: 'vecjar/python-aca-app:latest' # Docker Hub image

steps:

# -------------------------------------------------------------------
# Uses Python 3.11
# -------------------------------------------------------------------
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

# -------------------------------------------------------------------
# Installs Python dependencies
# -------------------------------------------------------------------
- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt
  displayName: 'Install Python dependencies'
  
# -------------------------------------------------------------------
# Builds and Pushes Docker Image to Docker Hub
# -------------------------------------------------------------------
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: 'vecjar/python-aca-app'
    dockerfile: 'app/Dockerfile'
    containerRegistry: 'DockerHub'   # Service connection name in devops
    tags: 'latest'
